Document: pkpgcounter
Title: Debian pkpgcounter Manual
Author: <insert document author here>
Abstract: This manual describes what pkpgcounter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pkpgcounter/pkpgcounter.sgml.gz

Format: postscript
Files: /usr/share/doc/pkpgcounter/pkpgcounter.ps.gz

Format: text
Files: /usr/share/doc/pkpgcounter/pkpgcounter.text.gz

Format: HTML
Index: /usr/share/doc/pkpgcounter/html/index.html
Files: /usr/share/doc/pkpgcounter/html/*.html

  
